title: "ion-book, La Comunidad de Ionic Framework en espa√±ol"
description: "Aprende Ionic y desarrolla increibles apps para Android y IOS."
keywords: "ion-book,html5,javascript,mobile,ionic,hybrid,phonegap,cordova,native,ios,android,angularjs,ionic 2,angular 2,curso de ionic 2, aprender ionic 2, ionic 3, ionic framework,hacer aplicaciones con ionic,aplicaciones hibridas, angular 4"

baseurl: ""
urlblog: '/blog'
cover: "/images/cover.jpg"
path: 'https://www.ion-book.com/'

timezone: "America/Bogota"

markdown: kramdown
permalink: blog/:categories/:title/
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
sass:
    style: compressed
excerpt_separator: <!--summary-->
exclude: [CNAME,'*.sh','*.json','README.md']