# Site settings
title: ion-book
email: ing.carlosandresrojas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://carlosrojaso.github.io" # the base hostname & protocol for your site
twitter_username: carlosrojas_o
github_username: carlosrojaso

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
